import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import React from 'react';
import GradientBackground from '@/app/gradient_background';
import { gradients } from '@/lib/constants/lists';
import { SupertokensInit } from '../components/supertokens_init';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SupertokensInit>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <GradientBackground
            gradients={gradients}
            title="Welcome to"
            subtitle="Project Management"
          />
          {children}
        </body>
      </SupertokensInit>
    </html>
  );
}
